MtEmber_RubyPath_B2F_Text_YWIntro::
    .string "Ni Bao and I won't let you take \n"
    .string "SY from me!$"


MtEmber_RubyPath_B2F_Text_YWDefeat::
    .string "You are destined to be together!\n"
    .string "Forward with my blessing!$"

MtEmber_RubyPath_B2F_YWPostBattle::
    .string "New advecture is waiting for you!$"

ViridianCity_Gym_Text_JasonIntro::
    .string "POKéMON and I, we make wonderful\n"
    .string "music together!$"

ViridianCity_Gym_Text_JasonDefeat::
    .string "You are in perfect harmony!$"

ViridianCity_Gym_Text_JasonPostBattle::
    .string "Do you know the identity of our\n"
    .string "GYM LEADER?$"
