Route6_Text_RickyIntro::
    .string "Who's there?\n"
    .string "Quit listening in on us!$"

Route6_Text_RickyDefeat::
    .string "I just can't win!$"

Route6_Text_RickyPostBattle::
    .string "Whisper…\n"
    .string "Whisper…$"

Route6_Text_NancyIntro::
    .string "Excuse me!\n"
    .string "This is a private conversation!$"

Route6_Text_NancyDefeat::
    .string "Ugh!\n"
    .string "I hate losing.$"

Route6_Text_NancyPostBattle::
    .string "Whisper…\n"
    .string "Whisper…$"

Route6_Text_KeigoIntro::
    .string "I know the secret of the comet…\n"
    .string "I won’t let you pass!$"

Route6_Text_KeigoDefeat::
    .string "You can have the comet,\n"
    .string "but I’ll see you again soon!$"

Route6_Text_KeigoPostBattle::
    .string "I once had a promise…$"

Route6_Text_JeffIntro::
    .string "Huh?\n"
    .string "You want to talk to me?$"

Route6_Text_JeffDefeat::
    .string "This stinks…\n"
    .string "I couldn't beat your challenge…$"

Route6_Text_JeffPostBattle::
    .string "I should bring more POKéMON with\n"
    .string "me. I'll feel safer that way.$"

Route6_Text_IsabelleIntro::
    .string "Me?\n"
    .string "Well, okay. I'll play!$"

Route6_Text_IsabelleDefeat::
    .string "Things just didn't work…$"

Route6_Text_IsabellePostBattle::
    .string "I want to get stronger.\n"
    .string "What's your secret?$"

Route6_Text_ElijahIntro::
    .string "I've never seen you around.\n"
    .string "Are you good?$"

Route6_Text_ElijahDefeat::
    .string "You're too good!$"

Route6_Text_ElijahPostBattle::
    .string "Are my POKéMON weak?\n"
    .string "Or, am I just bad?\l"
    .string "Which do you think?$"

Route6_Text_UndergroundPathSign::
    .string "UNDERGROUND PATH\n"
    .string "CERULEAN CITY - VERMILION CITY$"

